"""The episode store — the streams of one run, joined later.

Written from the first run, since nothing can be learned later from what was never
recorded, so this lands before the things it records (`ARCHITECTURE.md` §4).

    ticks       2 Hz + events   what was true, what was armed, and who armed it
    decisions   per call        what was asked, what came back, what it cost
    skills      per skill       how each armed skill actually ended
    executions  per operation   what the body did and saw inside an arm

They are separate streams because they have different rates, different authors and
different lifetimes. A tick is cheap and constant. A decision is rare and expensive. The
grades a learner wrote sixty seconds after each decision went with the decision student
(V224); what they graded is still written.

Format: JSONL, flushed per row.
-------------------------------
Append-only JSONL, flushed per row: a client that crashes — which is the normal way a run
ends — must not take the tail of the corpus with it. The corpus is the one artifact that
cannot be regenerated by running again, so the hot path trades throughput for durability.
"""

from __future__ import annotations

import json
import os
import pathlib
import threading
import time
import uuid
from dataclasses import asdict, dataclass, field
from enum import StrEnum
from typing import Any

from jev.world.state_v1 import ArmedBy

STORE_VERSION = 1


class Stream(StrEnum):
    TICKS = "ticks"
    DECISIONS = "decisions"
    SKILLS = "skills"
    EXECUTIONS = "executions"


# --------------------------------------------------------------------------- rows


@dataclass(frozen=True)
class TickRow:
    """One observation. `armed_by` is not optional, ever.

    Without it you cannot tell whose decision a row represents, and a corpus you cannot
    attribute is not a training set no matter how large it is.
    """

    run_id: str
    tick_id: int
    t: float
    client_id: str
    state: dict[str, Any]
    situation_key: str

    armed_skill: str | None
    # The *intent*, not just the skill. Without it, Gate C's agreement can only be
    # recovered on the single tick a decision acted on — not on the ticks that decision
    # keeps driving — so the headline agreement number would be measured over a minority
    # of the run and silently called the whole of it.
    armed_intent: str | None
    armed_by: ArmedBy
    keys: list[str] = field(default_factory=list)

    # What a local decision policy *would* have chosen, on every tick. No policy is left to
    # predict (V224), so every row abstains; the columns stay so the corpus keeps one schema.
    shadow_intent: str | None = None
    shadow_skill: str | None = None
    shadow_confidence: float | None = None
    shadow_model: str | None = None

    decision_id: str | None = None   # set when this tick is the one a decision acted on
    tracker_event: str | None = None
    tracker_from: str | None = None
    arm_id: str | None = None


@dataclass(frozen=True)
class DecisionRow:
    """One coach or teacher call. Written whether or not it was used."""

    run_id: str
    decision_id: str
    tick_id: int
    t: float
    client_id: str
    situation_key: str

    author: ArmedBy                  # POLICY or TEACHER
    model: str | None                # "claude-sub", "glm-4.6", "policy:v3", ...
    intent: str | None
    skill: str | None
    params: dict[str, Any] = field(default_factory=dict)
    confidence: float | None = None
    why: str | None = None

    # A request that never completed is not a decision. Transport failure, timeout,
    # abstention and refusal are four different things and none of them is an answer,
    # so each is recorded distinctly rather than collapsing into a null response.
    status: str = "ok"               # ok | timeout | transport | abstained | rejected
    verifier_verdict: str | None = None
    verifier_reason: str | None = None

    latency_ms: float | None = None
    tokens_in: int | None = None
    tokens_out: int | None = None

    # True when this answer came from the cache rather than the model. The saving is the
    # point of `situation_key`, so it has to be visible in the numbers.
    cache_hit: bool = False
    dedup_of: str | None = None      # the decision_id this was coalesced onto

    # Which escalation produced this answer. `dedup_of` links duplicate *questions*;
    # this links a teacher answer back to the coach tick that could not settle it.
    # Without it `unresolved/h` — the headline metric — has to be reconstructed by
    # joining on (run_id, situation_key, tick_id), which over-counts whenever one client
    # escalates the same bucket twice on one tick.
    escalated_from: str | None = None

    # Durable artifacts the teacher produced: skill drafts, graph patches, on_fail edges.
    # `DECISIONS.md` V11 makes these the *preferred* output — a decision helps one client
    # once, a skill helps every client forever — and on a rate-limited teacher that
    # difference is the whole economics. Recording only the immediate action would leave
    # the thing we actually optimise for invisible in the corpus, and a ratio nobody can
    # compute is a ratio nobody improves.
    artifacts: list[dict[str, Any]] = field(default_factory=list)


class SkillOutcome(StrEnum):
    SUCCEEDED = "succeeded"    # the skill's own success predicate fired
    TIMED_OUT = "timed_out"    # ran to its declared timeout without succeeding
    ABORTED = "aborted"        # an abort_if condition tripped
    PREEMPTED = "preempted"    # something more urgent took the body
    UNKNOWN = "unknown"        # the run ended mid-skill; not evidence either way


@dataclass(frozen=True)
class SkillResultRow:
    """How one armed skill actually ended.

    A fourth stream, because nothing else could answer the question. Decisions and grades
    cover skills armed through a coach or teacher decision; skills the tracker or System 1
    armed mechanically — which is most of them — wrote no decision row and so had no
    outcome to join to. The eval board reported every skill as `ungraded` and PLAN §10's
    retirement rule, "success rate below 0.4 over 20", had nothing to compute a rate from.

    `PREEMPTED` is deliberately not a failure. A skill that was interrupted by a corpse
    run did not fail at its job; counting it as failure would retire exactly the skills
    that run in dangerous places.
    """

    run_id: str
    client_id: str
    t: float
    tick_id: int
    skill: str
    armed_by: ArmedBy
    outcome: SkillOutcome
    duration_s: float
    situation_key: str
    step_id: str | None = None
    detail: str | None = None
    decision_id: str | None = None
    arm_id: str | None = None

    @property
    def counts_toward_rate(self) -> bool:
        """Only outcomes that say something about the skill itself."""
        return self.outcome in (SkillOutcome.SUCCEEDED, SkillOutcome.TIMED_OUT,
                                SkillOutcome.ABORTED)

    @property
    def succeeded(self) -> bool:
        return self.outcome is SkillOutcome.SUCCEEDED


@dataclass(frozen=True)
class ExecutionEventRow:
    """An observed operation within an arm, never another strategic decision.

    Begin/end rows share an operation ID; point events have their own ID and reference
    the enclosing operation. Native result codes remain evidence, not reward labels.
    """

    run_id: str
    client_id: str
    arm_id: str | None
    decision_id: str | None
    armed_by: ArmedBy
    step_id: str | None
    situation_key: str
    event_id: str
    operation_id: str
    parent_operation_id: str | None
    t: float
    tick_id: int
    phase: str
    operation: str
    code: str = ""
    detail: str = ""
    duration_s: float | None = None
    data: dict[str, Any] = field(default_factory=dict)


# --------------------------------------------------------------------------- writer


class Recorder:
    """Append-only JSONL, one file per stream per run, flushed per row.

    Deliberately boring. The flight recorder is the one component whose failure is
    invisible until the day you need the data and it is not there, so it does nothing
    clever: no buffering, no background thread, no schema negotiation.
    """

    def __init__(self, root: str | pathlib.Path = "runs", run_id: str | None = None) -> None:
        self.run_id = run_id or f"{time.strftime('%Y%m%dT%H%M%S')}-{uuid.uuid4().hex[:6]}"
        self.dir = pathlib.Path(root) / self.run_id
        self.dir.mkdir(parents=True, exist_ok=True)
        self._files: dict[Stream, Any] = {}
        self._tick_id = 0
        self._writing = threading.RLock()
        self._closed = False
        self._write_manifest()

    def _write_manifest(self) -> None:
        (self.dir / "manifest.json").write_text(
            json.dumps(
                {
                    "run_id": self.run_id,
                    "store_version": STORE_VERSION,
                    "started_at": time.time(),
                    "pid": os.getpid(),
                },
                indent=2,
            ),
            encoding="utf-8",
        )

    def _handle(self, stream: Stream):
        if stream not in self._files:
            self._files[stream] = (self.dir / f"{stream.value}.jsonl").open(
                "a", encoding="utf-8"
            )
        return self._files[stream]

    def _write(self, stream: Stream, row: Any) -> None:
        with self._writing:
            if self._closed:
                raise RuntimeError("recorder is closed")
            h = self._handle(stream)
            h.write(json.dumps(asdict(row), default=str) + "\n")
            h.flush()

    def next_tick_id(self) -> int:
        with self._writing:
            if self._closed:
                raise RuntimeError("recorder is closed")
            self._tick_id += 1
            return self._tick_id

    @property
    def tick_id(self) -> int:
        with self._writing:
            return self._tick_id

    def tick(self, row: TickRow) -> None:
        self._write(Stream.TICKS, row)

    def decision(self, row: DecisionRow) -> None:
        self._write(Stream.DECISIONS, row)

    def skill_result(self, row: SkillResultRow) -> None:
        self._write(Stream.SKILLS, row)

    def execution(self, row: ExecutionEventRow) -> None:
        self._write(Stream.EXECUTIONS, row)

    def close(self) -> None:
        with self._writing:
            self._closed = True
            error = None
            for h in self._files.values():
                try:
                    h.close()
                except Exception as exc:
                    error = error or exc
            self._files.clear()
            if error is not None:
                raise error

    def __enter__(self) -> Recorder:
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()


def read(path: str | pathlib.Path) -> list[dict[str, Any]]:
    """Read one JSONL stream back. Tolerates a truncated final line, because the normal
    way a run ends is a crash mid-write and one lost tick must not cost the run."""
    rows: list[dict[str, Any]] = []
    with pathlib.Path(path).open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                break
    return rows
