"""The episode store — three streams, joined later.

Written from the first run or distillation is impossible later, so this lands before the
things it records (`ARCHITECTURE.md` §4).

    ticks      2 Hz + events   what was true, what was armed, and who armed it
    decisions  per call        what was asked, what came back, what it cost
    grades     written later   what actually happened next

They are separate streams because they have different rates, different authors and
different lifetimes. A tick is cheap and constant. A decision is rare and expensive. A
grade cannot exist until sixty seconds after the thing it grades, so inlining it into
either would mean holding rows open — and a held-open row is a row you lose in a crash.

Format: JSONL on the hot path, parquet in batch.
-----------------------------------------------
Append-only JSONL, flushed per row. Parquet writers buffer into row groups, so a client
that crashes — which is the normal way a run ends — takes the tail of the corpus with it.
The corpus is the one artifact that cannot be regenerated by running again, so the hot
path trades throughput for durability and the learner converts to parquet in batch.
"""

from __future__ import annotations

import json
import os
import pathlib
import time
import uuid
from dataclasses import asdict, dataclass, field
from enum import StrEnum
from typing import Any

from jev.world.state_v1 import ArmedBy, State

STORE_VERSION = 1


class Stream(StrEnum):
    TICKS = "ticks"
    DECISIONS = "decisions"
    GRADES = "grades"


class Outcome(StrEnum):
    """Why a decision stopped being interesting. Not all of these are failures."""

    ADVANCED = "advanced"      # the step completed — the outcome we pay for
    LEVELED = "leveled"        # dinged during the window
    DIED = "died"
    STUCK = "stuck"
    NO_CHANGE = "no_change"    # window elapsed, nothing moved
    ABANDONED = "abandoned"    # run ended inside the window; not evidence either way


# --------------------------------------------------------------------------- rows


@dataclass(frozen=True)
class TickRow:
    """One observation. `armed_by` is not optional, ever.

    Without it you cannot tell whose decision a row represents, and a corpus you cannot
    attribute is not a training set no matter how large it is.
    """

    run_id: str
    tick_id: int
    t: float
    client_id: str
    state: dict[str, Any]
    situation_key: str

    armed_skill: str | None
    armed_by: ArmedBy
    keys: list[str] = field(default_factory=list)

    # What the local policy *would* have chosen, on every tick, including ticks it is not
    # driving. This is the agreement metric; a 90% gate is only measurable if it was
    # measured all along rather than switched on at the end.
    shadow_intent: str | None = None
    shadow_skill: str | None = None
    shadow_confidence: float | None = None

    decision_id: str | None = None   # set when this tick is the one a decision acted on


@dataclass(frozen=True)
class DecisionRow:
    """One coach or teacher call. Written whether or not it was used."""

    run_id: str
    decision_id: str
    tick_id: int
    t: float
    client_id: str
    situation_key: str

    author: ArmedBy                  # POLICY or TEACHER
    model: str | None                # "claude-sub", "glm-4.6", "policy:v3", ...
    intent: str | None
    skill: str | None
    params: dict[str, Any] = field(default_factory=dict)
    confidence: float | None = None
    why: str | None = None

    # A request that never completed is not a decision. Transport failure, timeout,
    # abstention and refusal are four different things and none of them is an answer,
    # so each is recorded distinctly rather than collapsing into a null response.
    status: str = "ok"               # ok | timeout | transport | abstained | rejected
    verifier_verdict: str | None = None
    verifier_reason: str | None = None

    latency_ms: float | None = None
    tokens_in: int | None = None
    tokens_out: int | None = None

    # True when this answer came from the cache rather than the model. The saving is the
    # point of `situation_key`, so it has to be visible in the numbers.
    cache_hit: bool = False
    dedup_of: str | None = None      # the decision_id this was coalesced onto


@dataclass(frozen=True)
class GradeRow:
    """What happened in the window after a decision. Written by the grader, not the client."""

    run_id: str
    decision_id: str
    tick_id: int
    window_s: float

    outcome: Outcome
    step_advanced: bool
    level_progress_delta: float      # (level + xp_pct) delta; monotone across dings
    died: bool
    stuck_s: float
    off_route_s: float
    reward: float

    # The training filter. A decision is only an example if what followed it was good —
    # which is what lets a wrong teacher call cost nothing (ARCHITECTURE.md §2).
    good: bool


# --------------------------------------------------------------------------- reward


def level_progress(state: State) -> float | None:
    """A single monotone scalar for progress. `xp_pct` alone resets at every ding."""
    lvl, pct = state.char.level, state.char.xp_pct
    if lvl is None:
        return None
    return lvl + (pct or 0.0)


def reward(
    *,
    step_advanced: bool,
    level_progress_delta: float,
    died: bool,
    stuck_s: float,
    off_route_s: float,
    skippable: bool = False,
) -> float:
    """PLAN §7.1, with the weights it names.

    Step advance leads deliberately. Rewarding XP alone teaches grinding in place, and
    rewarding survival alone teaches standing still: a policy that never moves never dies.
    """
    if skippable:
        return 0.0
    return (
        (1.0 if step_advanced else 0.0)
        + level_progress_delta
        - (1.0 if died else 0.0)
        - (1.0 if stuck_s > 15.0 else 0.0)
        - 0.2 * (off_route_s / 10.0)
    )


def grade(
    decision: DecisionRow,
    window: list[TickRow],
    *,
    window_s: float = 60.0,
    run_ended: bool = False,
) -> GradeRow:
    """Join a decision to the ticks that followed it.

    `run_ended` matters: a window cut short by the process dying is not evidence that the
    decision was bad. It is `ABANDONED`, and it does not become a training example either
    way — absence of an outcome is not a bad outcome.
    """
    states = [State.model_validate(t.state) for t in window]

    died = any(s.vitals.dead is True or s.vitals.ghost is True for s in states)
    steps = [s.guide.step_id for s in states if s.guide.step_id]
    step_advanced = bool(steps) and steps[-1] != steps[0]

    progress = [p for p in (level_progress(s) for s in states) if p is not None]
    delta = (progress[-1] - progress[0]) if len(progress) >= 2 else 0.0

    off_route_s = _duration_where(window, states, lambda s: s.guide.on_route is False)
    stuck_s = _duration_where(window, states, lambda s: s.control.s1_mode == "stuck")

    if run_ended and not (step_advanced or died):
        outcome = Outcome.ABANDONED
    elif died:
        outcome = Outcome.DIED
    elif step_advanced:
        outcome = Outcome.ADVANCED
    elif delta >= 1.0:
        outcome = Outcome.LEVELED
    elif stuck_s > 15.0:
        outcome = Outcome.STUCK
    else:
        outcome = Outcome.NO_CHANGE

    r = reward(
        step_advanced=step_advanced,
        level_progress_delta=delta,
        died=died,
        stuck_s=stuck_s,
        off_route_s=off_route_s,
    )

    return GradeRow(
        run_id=decision.run_id,
        decision_id=decision.decision_id,
        tick_id=decision.tick_id,
        window_s=window_s,
        outcome=outcome,
        step_advanced=step_advanced,
        level_progress_delta=delta,
        died=died,
        stuck_s=stuck_s,
        off_route_s=off_route_s,
        reward=r,
        # An abandoned window is not evidence, so it is never an example. A decision that
        # was never actually executed is not evidence about the decision either.
        good=(outcome is not Outcome.ABANDONED and decision.status == "ok" and r > 0.0),
    )


def _duration_where(rows: list[TickRow], states: list[State], pred) -> float:
    """Seconds spent in states matching `pred`, by trapezoid over tick timestamps."""
    total = 0.0
    for i in range(len(rows) - 1):
        if pred(states[i]):
            total += rows[i + 1].t - rows[i].t
    return total


# --------------------------------------------------------------------------- writer


class Recorder:
    """Append-only JSONL, one file per stream per run, flushed per row.

    Deliberately boring. The flight recorder is the one component whose failure is
    invisible until the day you need the data and it is not there, so it does nothing
    clever: no buffering, no background thread, no schema negotiation.
    """

    def __init__(self, root: str | pathlib.Path = "runs", run_id: str | None = None) -> None:
        self.run_id = run_id or f"{time.strftime('%Y%m%dT%H%M%S')}-{uuid.uuid4().hex[:6]}"
        self.dir = pathlib.Path(root) / self.run_id
        self.dir.mkdir(parents=True, exist_ok=True)
        self._files: dict[Stream, Any] = {}
        self._tick_id = 0
        self._write_manifest()

    def _write_manifest(self) -> None:
        (self.dir / "manifest.json").write_text(
            json.dumps(
                {
                    "run_id": self.run_id,
                    "store_version": STORE_VERSION,
                    "started_at": time.time(),
                    "pid": os.getpid(),
                },
                indent=2,
            ),
            encoding="utf-8",
        )

    def _handle(self, stream: Stream):
        if stream not in self._files:
            self._files[stream] = (self.dir / f"{stream.value}.jsonl").open(
                "a", encoding="utf-8"
            )
        return self._files[stream]

    def _write(self, stream: Stream, row: Any) -> None:
        h = self._handle(stream)
        h.write(json.dumps(asdict(row), default=str) + "\n")
        h.flush()

    def next_tick_id(self) -> int:
        self._tick_id += 1
        return self._tick_id

    def tick(self, row: TickRow) -> None:
        self._write(Stream.TICKS, row)

    def decision(self, row: DecisionRow) -> None:
        self._write(Stream.DECISIONS, row)

    def gradation(self, row: GradeRow) -> None:
        self._write(Stream.GRADES, row)

    def close(self) -> None:
        for h in self._files.values():
            h.close()
        self._files.clear()

    def __enter__(self) -> Recorder:
        return self

    def __exit__(self, *exc: object) -> None:
        self.close()


def read(path: str | pathlib.Path) -> list[dict[str, Any]]:
    """Read one JSONL stream back. Tolerates a truncated final line, because the normal
    way a run ends is a crash mid-write and one lost tick must not cost the run."""
    rows: list[dict[str, Any]] = []
    with pathlib.Path(path).open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                break
    return rows
