"""Batch conversion of the JSONL streams to parquet, for training.

The hot path writes JSONL deliberately: a run normally ends in a crash, parquet buffers
into row groups, and a buffered row group is the tail of the corpus you never get back
(`jev/learn/episode.py`). That trade is right on a live client and wrong for a learner
reading eight hours of ticks off disk, so this is the other half of it — the nightly/idle
converter.

Three things it must not do, each of which is a way of losing a corpus that cannot be
regenerated by running again:

* **It must not infer the schema.** Inference on nullable nested data gives you a schema
  per file: a field nobody observed on Tuesday is `null`-typed on Tuesday and `double`-typed
  on Wednesday, and the two files will not concatenate. The schemas here are declared, so
  every file in the store has the same one and an empty stream still produces a readable,
  concatenable table.
* **It must not drop columns it does not recognise.** A client running a newer schema
  writes fields this converter has never heard of; they are kept verbatim in `extra_json`
  rather than discarded, so the conversion is lossless and a schema change is visible
  afterwards instead of silently absent.
* **It must not delete the JSONL.** The original is the durable artifact. Deleting it on
  successful conversion makes this module a single point of failure for everything ever
  recorded.

`state` and `params` are stored as JSON strings rather than as parquet structs. Same
reason as the first point, sharpened: `state_v1` is 57 mostly-optional fields across
twelve nested models, and its inferred struct type differs run to run. The join and filter
columns — run, tick, time, client, `situation_key`, `armed_by` — are typed and columnar,
which is what the learner actually scans on; the state is opened by the featuriser after
the rows are chosen.
"""

from __future__ import annotations

import json
import pathlib
from collections.abc import Iterator
from typing import Any

import pyarrow as pa
import pyarrow.parquet as pq

from jev.learn.episode import Stream

COMPRESSION = "zstd"
"""Over snappy: the corpus is written once and read in batch by a job with time to spare,
so roughly half the bytes for decompression that still outruns the featuriser is the right
side of that trade. Over none: these files are kept forever."""

ROW_GROUP = 20_000
"""A row group is the unit parquet reads and skips. 20k ticks is a few megabytes — small
enough that a filtered scan skips most of the file, large enough that the footer does not
become the file."""

JSON_COLUMNS = frozenset({"state", "params"})
EXTRA = "extra_json"


def _json_str() -> pa.DataType:
    return pa.string()


TICKS_SCHEMA = pa.schema([
    ("run_id", pa.string()),
    ("tick_id", pa.int64()),
    ("t", pa.float64()),
    ("client_id", pa.string()),
    ("state", _json_str()),
    ("situation_key", pa.string()),
    ("armed_skill", pa.string()),
    ("armed_by", pa.string()),
    ("keys", pa.list_(pa.string())),
    ("shadow_intent", pa.string()),
    ("shadow_skill", pa.string()),
    ("shadow_confidence", pa.float64()),
    ("decision_id", pa.string()),
    (EXTRA, pa.string()),
])

DECISIONS_SCHEMA = pa.schema([
    ("run_id", pa.string()),
    ("decision_id", pa.string()),
    ("tick_id", pa.int64()),
    ("t", pa.float64()),
    ("client_id", pa.string()),
    ("situation_key", pa.string()),
    ("author", pa.string()),
    ("model", pa.string()),
    ("intent", pa.string()),
    ("skill", pa.string()),
    ("params", _json_str()),
    ("confidence", pa.float64()),
    ("why", pa.string()),
    ("status", pa.string()),
    ("verifier_verdict", pa.string()),
    ("verifier_reason", pa.string()),
    ("latency_ms", pa.float64()),
    ("tokens_in", pa.int64()),
    ("tokens_out", pa.int64()),
    ("cache_hit", pa.bool_()),
    ("dedup_of", pa.string()),
    (EXTRA, pa.string()),
])

GRADES_SCHEMA = pa.schema([
    ("run_id", pa.string()),
    ("decision_id", pa.string()),
    ("tick_id", pa.int64()),
    ("window_s", pa.float64()),
    ("outcome", pa.string()),
    ("step_advanced", pa.bool_()),
    ("level_progress_delta", pa.float64()),
    ("died", pa.bool_()),
    ("stuck_s", pa.float64()),
    ("off_route_s", pa.float64()),
    ("reward", pa.float64()),
    ("good", pa.bool_()),
    (EXTRA, pa.string()),
])

SCHEMAS: dict[Stream, pa.Schema] = {
    Stream.TICKS: TICKS_SCHEMA,
    Stream.DECISIONS: DECISIONS_SCHEMA,
    Stream.GRADES: GRADES_SCHEMA,
}


def iter_rows(path: str | pathlib.Path) -> Iterator[dict[str, Any]]:
    """Stream one JSONL file, stopping at the first torn line.

    Same tolerance as `episode.read` and the same reason — the normal way a run ends is a
    crash mid-write — but streaming rather than materialising, because this converter is
    handed whole nights of ticks and `read` would want all of them resident at once. The
    stopping rule is duplicated in one line rather than shared, so if it ever grows past
    one line, share it.
    """
    with pathlib.Path(path).open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line:
                continue
            try:
                yield json.loads(line)
            except json.JSONDecodeError:
                return


def _normalise(row: dict[str, Any], schema: pa.Schema) -> dict[str, Any]:
    """One JSONL row as one parquet row: declared columns typed, everything else kept."""
    declared = set(schema.names) - {EXTRA}
    out: dict[str, Any] = {}
    for name in declared:
        v = row.get(name)
        if name in JSON_COLUMNS:
            out[name] = None if v is None else json.dumps(v)
        else:
            out[name] = v
    if out.get("keys") is None and "keys" in declared:
        out["keys"] = []
    leftovers = {k: v for k, v in row.items() if k not in declared}
    out[EXTRA] = json.dumps(leftovers) if leftovers else None
    return out


def _denormalise(row: dict[str, Any]) -> dict[str, Any]:
    out = dict(row)
    extra = out.pop(EXTRA, None)
    for name in JSON_COLUMNS & set(out):
        if isinstance(out[name], str):
            out[name] = json.loads(out[name])
    if extra:
        out.update(json.loads(extra))
    return out


def convert_stream(
    jsonl_path: str | pathlib.Path,
    parquet_path: str | pathlib.Path,
    stream: Stream,
) -> int:
    """Convert one stream. Returns the row count written.

    A stream with no rows still produces a file, with the declared schema and nothing in
    it. An absent file and an empty one mean different things to a job scanning the store,
    and only one of them can be told apart from a converter that failed silently.
    """
    schema = SCHEMAS[stream]
    src, dst = pathlib.Path(jsonl_path), pathlib.Path(parquet_path)
    dst.parent.mkdir(parents=True, exist_ok=True)

    written = 0
    batch: list[dict[str, Any]] = []
    with pq.ParquetWriter(dst, schema, compression=COMPRESSION) as writer:
        for row in iter_rows(src) if src.exists() else ():
            batch.append(_normalise(row, schema))
            if len(batch) >= ROW_GROUP:
                writer.write_table(pa.Table.from_pylist(batch, schema=schema))
                written += len(batch)
                batch = []
        if batch or written == 0:
            writer.write_table(pa.Table.from_pylist(batch, schema=schema))
            written += len(batch)
    return written


def convert_run(
    run_dir: str | pathlib.Path,
    *,
    out_dir: str | pathlib.Path | None = None,
    force: bool = False,
) -> dict[Stream, pathlib.Path]:
    """Convert every stream of one run, next to the JSONL unless told otherwise.

    Skips a stream whose parquet is already newer than its JSONL, so the nightly job is
    safe to re-run over the whole store — which it will be, because the alternative is
    remembering which nights were already done.
    """
    src_dir = pathlib.Path(run_dir)
    dst_dir = pathlib.Path(out_dir) if out_dir is not None else src_dir
    out: dict[Stream, pathlib.Path] = {}
    for stream in Stream:
        jsonl = src_dir / f"{stream.value}.jsonl"
        if not jsonl.exists():
            continue
        parquet = dst_dir / f"{stream.value}.parquet"
        if not force and parquet.exists() and parquet.stat().st_mtime >= jsonl.stat().st_mtime:
            out[stream] = parquet
            continue
        convert_stream(jsonl, parquet, stream)
        out[stream] = parquet
    return out


def convert_store(
    root: str | pathlib.Path, *, force: bool = False
) -> dict[str, dict[Stream, pathlib.Path]]:
    """Convert every run directory under `root`. One bad run does not stop the others —
    a converter that aborts the night on the first truncated file converts nothing."""
    done: dict[str, dict[Stream, pathlib.Path]] = {}
    for d in sorted(p for p in pathlib.Path(root).iterdir() if p.is_dir()):
        if not any((d / f"{s.value}.jsonl").exists() for s in Stream):
            continue
        done[d.name] = convert_run(d, force=force)
    return done


def read_parquet(path: str | pathlib.Path) -> list[dict[str, Any]]:
    """Read a converted stream back into the row dicts the JSONL held.

    The inverse of `convert_stream`, exactly: JSON columns are parsed, `extra_json` is
    merged back in. Everything downstream — the eval board, the dataset builder — consumes
    rows of this shape, so parquet and JSONL are interchangeable inputs rather than two
    code paths that drift.
    """
    table = pq.read_table(path)
    return [_denormalise(r) for r in table.to_pylist()]
