#!/usr/bin/env python3
"""Generate the addon's field table and build the addon a client installs.

The field table exists once, in Python (`jev/perceive/fields.py`). Its Lua copy,
`addons/JevRadio/Fields.lua`, is generated and gitignored, so the two cannot drift
(`DECISIONS.md` V13); `tests/test_generated_lua.py` fails when it is stale.

What a client installs is not the source folder. The sources are module bodies - each
returns a table and defines nothing global - and the build joins them into one file, each
part in its own function scope, comments stripped, under a neutral name and title. The
installed addon owns no global names, names no frame, and carries no project name in its
folder, table of contents or code.

Usage:  python tools/gen_addon_fields.py [--check] [--install [ADDONS_DIR]]
"""

from __future__ import annotations

import argparse
import datetime
import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from jev.perceive.fields import (  # noqa: E402
    BITS_PER_CHANNEL,
    CALIBRATION_SWATCHES,
    CHECKSUM_BITS,
    FIELDS,
    GRID_COLS,
    GRID_ROWS,
    LEVELS,
    MARKER_L,
    MARKER_R,
    STEP,
    layout,
)

SOURCE = ROOT / "addons" / "JevRadio"
OUT = SOURCE / "Fields.lua"
BUILD = ROOT / "build" / "addon"

# What the client sees: the folder, the table of contents and the one file.
ADDON_NAME = "StatusStrip"
ADDON_TITLE = "Status Strip"
ADDON_NOTES = "Compact status display."
INTERFACE = 20400

# Build order is dependency order: each part is a function over the tables the parts
# before it returned. The painter comes last and returns nothing.
PARTS = (
    ("Supplies", "Supplies.lua", ()),
    ("Helpers", "Helpers.lua", ("Supplies",)),
    ("Fields", "Fields.lua", ()),
    (None, "JevRadio.lua", ("Helpers", "Fields")),
)

# Earlier installs used the project's own name; installing replaces them.
LEGACY_NAMES = ("JevRadio",)
DEFAULT_ADDONS = "/mnt/c/Games/WoW243/Interface/AddOns"


def _indent(body: str, pad: str = "    ") -> str:
    return "\n".join(pad + line if line else "" for line in body.strip().split("\n"))


def render() -> str:
    """`Fields.lua`: a module body returning the layout, calibration and field table."""
    lay = layout()
    lines: list[str] = [
        "-- GENERATED by tools/gen_addon_fields.py. Do not edit.",
        "-- Source of truth: jev/perceive/fields.py",
        "--",
        "-- Editing this file is a build error: the decoder reads the Python table and the",
        "-- addon reads this one, so a hand change here is a silent disagreement between",
        "-- two halves of a wire format that has no way to notice.",
        "",
        "local layout = {",
        f"    schema           = {lay['schema']},",
        f"    bitsPerChannel   = {BITS_PER_CHANNEL},",
        f"    levels           = {LEVELS},",
        f"    step             = {STEP},",
        f"    cols             = {GRID_COLS},",
        f"    rows             = {GRID_ROWS},",
        f"    calibrationRows  = {lay['calibration_rows']},",
        f"    payloadCells     = {lay['payload_cells']},",
        f"    checksumBits     = {CHECKSUM_BITS},",
        "}",
        "",
        "local markers = {",
        f"    left  = {{{MARKER_L[0]}, {MARKER_L[1]}, {MARKER_L[2]}}},",
        f"    right = {{{MARKER_R[0]}, {MARKER_R[1]}, {MARKER_R[2]}}},",
        "}",
        "",
        "local swatches = {",
    ]
    lines += [f"    {{{r}, {g}, {b}}}," for r, g, b in CALIBRATION_SWATCHES]
    lines += [
        "}",
        "",
        "-- Wire order. Reordering is a schema break, appending is not.",
        "local fields = {",
    ]
    for f in FIELDS:
        lines.append("    {")
        lines.append(f'        name = "{f.name}", bits = {f.bits}, kind = "{f.kind.value}",')
        if f.note:
            lines.append(f"        -- {f.note}")
        lines.append("        get = function()")
        lines.append(_indent(f.lua, " " * 12))
        lines.append("        end,")
        lines.append("    },")
    lines += [
        "}",
        "",
        "return { layout = layout, markers = markers, swatches = swatches, fields = fields }",
        "",
    ]
    return "\n".join(lines)


_LONG_OPEN = re.compile(r"\[(=*)\[")
# A newline inside a string, shielded from the pass that drops blank lines and trailing
# spaces: inside a long string both are part of its value.
_KEEP = "\0"


def strip_lua_comments(source: str) -> str:
    """Lua 5.1 source without comments, blank lines or trailing spaces, strings left
    exactly as written.

    A short scanner rather than a regex: `--` inside a string is not a comment, and a long
    comment or string (`[[ ]]`, `[==[ ]==]`) can span lines.
    """
    if _KEEP in source:
        raise ValueError("Lua source with a NUL byte in it")
    out: list[str] = []
    i, n = 0, len(source)
    while i < n:
        c = source[i]
        if source.startswith("--", i):
            long = _LONG_OPEN.match(source, i + 2)
            if long:
                close = "]" + long.group(1) + "]"
                end = source.find(close, long.end())
                i = n if end < 0 else end + len(close)
            else:
                end = source.find("\n", i)
                i = n if end < 0 else end
            continue
        if c in "'\"":
            j = i + 1
            while j < n and source[j] != c and source[j] != "\n":
                j += 2 if source[j] == "\\" else 1
            out.append(source[i:j + 1].replace("\n", _KEEP))
            i = j + 1
            continue
        if c == "[":
            long = _LONG_OPEN.match(source, i)
            if long:
                close = "]" + long.group(1) + "]"
                end = source.find(close, long.end())
                end = n if end < 0 else end + len(close)
                out.append(source[i:end].replace("\n", _KEEP))
                i = end
                continue
        out.append(c)
        i += 1
    lines = [line.rstrip() for line in "".join(out).split("\n")]
    return "\n".join(line for line in lines if line.strip()).replace(_KEEP, "\n")


def bundle(fields_lua: str | None = None) -> str:
    """The one file a client loads. Each part runs in its own function scope over the
    tables the earlier parts returned, so nothing needs a global to reach anything."""
    chunks = []
    for name, file, needs in PARTS:
        text = fields_lua if file == "Fields.lua" and fields_lua is not None else \
            (SOURCE / file).read_text(encoding="utf-8")
        body = strip_lua_comments(text)
        params = ", ".join(needs)
        target = f"local {name}" if name else "local _"
        chunks.append(f"{target} = (function({params})\n{body}\nend)({params})")
    return "\n".join(chunks) + "\n"


def toc() -> str:
    # DefaultState as the earlier table of contents had it: the client lists neither
    # addon in AddOns.txt, and that form is the one measured to load unlisted.
    return (f"## Interface: {INTERFACE}\n## Title: {ADDON_TITLE}\n## Notes: {ADDON_NOTES}\n"
            f"## Version: 1.0.0\n## DefaultState: enabled\n{ADDON_NAME}.lua\n")


def build(dest_root: pathlib.Path = BUILD, fields_lua: str | None = None) -> pathlib.Path:
    """Write the installable addon folder under `dest_root` and return it.

    The folder is replaced, not updated: installing copies all of it, so a file left over
    from an older build would ship.
    """
    folder = dest_root / ADDON_NAME
    shutil.rmtree(folder, ignore_errors=True)
    folder.mkdir(parents=True)
    (folder / f"{ADDON_NAME}.toc").write_text(toc(), encoding="utf-8")
    (folder / f"{ADDON_NAME}.lua").write_text(bundle(fields_lua), encoding="utf-8")
    return folder


def install(addons_dir: pathlib.Path, built: pathlib.Path,
            backups: pathlib.Path = ROOT / "captures" / "addon-backup") -> pathlib.Path:
    """Replace the installed addon with `built`; earlier installs are moved, not deleted.

    Generating and installing are one step on purpose. The Lua is generated from
    `fields.py` precisely so the two sides cannot disagree, and copying it across by hand
    reintroduces that drift as a checksum failure on a client running last week's schema.
    """
    if not addons_dir.is_dir():
        raise SystemExit(f"no such AddOns directory: {addons_dir}")
    stamp = datetime.datetime.now(datetime.UTC).strftime("%Y%m%dT%H%M%S")
    for name in (*LEGACY_NAMES, ADDON_NAME):
        old = addons_dir / name
        if old.exists():
            keep = backups / f"{stamp}-{name}"
            n = 1
            while keep.exists():            # moving onto an existing folder nests inside it
                n += 1
                keep = backups / f"{stamp}-{name}-{n}"
            keep.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(old), str(keep))
    dest = addons_dir / ADDON_NAME
    shutil.copytree(built, dest)
    # Read back across the Windows mount: a short copy is a client painting last
    # week's schema, found as a checksum failure at the next login.
    for file in built.iterdir():
        if (dest / file.name).read_bytes() != file.read_bytes():
            raise SystemExit(f"installed {dest / file.name} does not match the build")
    return dest


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit non-zero if the file is stale")
    ap.add_argument("--install", metavar="ADDONS_DIR", nargs="?",
                    const=DEFAULT_ADDONS, default=None,
                    help="also install the built addon into a client's Interface/AddOns")
    args = ap.parse_args()

    want = render()
    if args.check:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have != want:
            print(f"stale: {OUT} does not match fields.py - run tools/gen_addon_fields.py")
            return 1
        print(f"up to date: {OUT}")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(want, encoding="utf-8")
    built = build()
    lay = layout()
    print(
        f"wrote {OUT} - {lay['field_count']} fields, {lay['payload_bits']} payload bits, "
        f"{lay['payload_cells']} cells in a {lay['cols']}x{lay['rows']} grid "
        f"({lay['spare_bits']} spare bits); built {built}"
    )
    if args.install:
        dest = install(pathlib.Path(args.install), built)
        print(f"installed to {dest}; the client loads it at the next login")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
