#!/usr/bin/env python3
"""Generate `addons/JevRadio/Fields.lua` from `jev/perceive/fields.py`.

The field table exists once, in Python. The addon's copy is generated from it and is
gitignored, so the two cannot drift (`DECISIONS.md` V13). Run this after touching
`fields.py`; `tests/test_generated_lua.py` fails if the checked-in generator output is
stale.

Usage:  python tools/gen_addon_fields.py [--check]
"""

from __future__ import annotations

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

from jev.perceive.fields import (
    BITS_PER_CHANNEL,
    CALIBRATION_SWATCHES,
    CHECKSUM_BITS,
    FIELDS,
    GRID_COLS,
    GRID_ROWS,
    LEVELS,
    MARKER_L,
    MARKER_R,
    STEP,
    layout,
)

OUT = pathlib.Path(__file__).resolve().parent.parent / "addons" / "JevRadio" / "Fields.lua"


def _indent(body: str, pad: str = "    ") -> str:
    return "\n".join(pad + line if line else "" for line in body.strip().split("\n"))


def render() -> str:
    lay = layout()
    lines: list[str] = [
        "-- GENERATED by tools/gen_addon_fields.py. Do not edit.",
        "-- Source of truth: jev/perceive/fields.py",
        "--",
        "-- Editing this file is a build error: the decoder reads the Python table and the",
        "-- addon reads this one, so a hand change here is a silent disagreement between",
        "-- two halves of a wire format that has no way to notice.",
        "",
        "JevRadioLayout = {",
        f"    schema           = {lay['schema']},",
        f"    bitsPerChannel   = {BITS_PER_CHANNEL},",
        f"    levels           = {LEVELS},",
        f"    step             = {STEP},",
        f"    cols             = {GRID_COLS},",
        f"    rows             = {GRID_ROWS},",
        f"    calibrationRows  = {lay['calibration_rows']},",
        f"    payloadCells     = {lay['payload_cells']},",
        f"    checksumBits     = {CHECKSUM_BITS},",
        "}",
        "",
        "JevRadioMarkers = {",
        f"    left  = {{{MARKER_L[0]}, {MARKER_L[1]}, {MARKER_L[2]}}},",
        f"    right = {{{MARKER_R[0]}, {MARKER_R[1]}, {MARKER_R[2]}}},",
        "}",
        "",
        "JevRadioSwatches = {",
    ]
    lines += [f"    {{{r}, {g}, {b}}}," for r, g, b in CALIBRATION_SWATCHES]
    lines += [
        "}",
        "",
        "-- Wire order. Reordering is a schema break, appending is not.",
        "JevRadioFields = {",
    ]

    for f in FIELDS:
        lines.append("    {")
        lines.append(f'        name = "{f.name}", bits = {f.bits}, kind = "{f.kind.value}",')
        if f.note:
            lines.append(f"        -- {f.note}")
        lines.append("        get = function()")
        lines.append(_indent(f.lua, " " * 12))
        lines.append("        end,")
        lines.append("    },")

    lines += ["}", ""]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="exit non-zero if the file is stale")
    args = ap.parse_args()

    want = render()
    if args.check:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have != want:
            print(f"stale: {OUT} does not match fields.py — run tools/gen_addon_fields.py")
            return 1
        print(f"up to date: {OUT}")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(want, encoding="utf-8")
    lay = layout()
    print(
        f"wrote {OUT} — {lay['field_count']} fields, {lay['payload_bits']} payload bits, "
        f"{lay['payload_cells']} cells in a {lay['cols']}x{lay['rows']} grid "
        f"({lay['spare_bits']} spare bits)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
